/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : BookingId,
  'customerName' : string,
  'status' : BookingStatus,
  'customerPhone' : string,
  'teamMemberId' : [] | [TeamMemberId],
  'createdAt' : Timestamp,
  'preferredDateTime' : string,
  'serviceId' : ServiceId,
  'customerEmail' : string,
}
export type BookingId = bigint;
export interface BookingRequest {
  'customerName' : string,
  'customerPhone' : string,
  'teamMemberId' : [] | [TeamMemberId],
  'preferredDateTime' : string,
  'serviceId' : ServiceId,
  'customerEmail' : string,
}
export type BookingResult = { 'ok' : Booking } |
  { 'err' : string };
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface Service {
  'id' : ServiceId,
  'name' : string,
  'description' : string,
  'durationMinutes' : bigint,
  'category' : ServiceCategory,
  'price' : bigint,
}
export type ServiceCategory = { 'fade' : null } |
  { 'haircut' : null } |
  { 'beardTrim' : null } |
  { 'lineup' : null };
export type ServiceId = bigint;
export interface TeamMember {
  'id' : TeamMemberId,
  'name' : string,
  'specialty' : string,
}
export type TeamMemberId = bigint;
export type Timestamp = bigint;
export interface _SERVICE {
  'cancelBooking' : ActorMethod<[BookingId], BookingResult>,
  'createBooking' : ActorMethod<[BookingRequest], BookingResult>,
  'getBooking' : ActorMethod<[BookingId], [] | [Booking]>,
  'getService' : ActorMethod<[ServiceId], [] | [Service]>,
  'getTeamMember' : ActorMethod<[TeamMemberId], [] | [TeamMember]>,
  'listBookings' : ActorMethod<[], Array<Booking>>,
  'listServices' : ActorMethod<[], Array<Service>>,
  'listTeamMembers' : ActorMethod<[], Array<TeamMember>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];