/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingId = IDL.Nat;
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const TeamMemberId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ServiceId = IDL.Nat;
export const Booking = IDL.Record({
  'id' : BookingId,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'customerPhone' : IDL.Text,
  'teamMemberId' : IDL.Opt(TeamMemberId),
  'createdAt' : Timestamp,
  'preferredDateTime' : IDL.Text,
  'serviceId' : ServiceId,
  'customerEmail' : IDL.Text,
});
export const BookingResult = IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text });
export const BookingRequest = IDL.Record({
  'customerName' : IDL.Text,
  'customerPhone' : IDL.Text,
  'teamMemberId' : IDL.Opt(TeamMemberId),
  'preferredDateTime' : IDL.Text,
  'serviceId' : ServiceId,
  'customerEmail' : IDL.Text,
});
export const ServiceCategory = IDL.Variant({
  'fade' : IDL.Null,
  'haircut' : IDL.Null,
  'beardTrim' : IDL.Null,
  'lineup' : IDL.Null,
});
export const Service = IDL.Record({
  'id' : ServiceId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'category' : ServiceCategory,
  'price' : IDL.Nat,
});
export const TeamMember = IDL.Record({
  'id' : TeamMemberId,
  'name' : IDL.Text,
  'specialty' : IDL.Text,
});

export const idlService = IDL.Service({
  'cancelBooking' : IDL.Func([BookingId], [BookingResult], []),
  'createBooking' : IDL.Func([BookingRequest], [BookingResult], []),
  'getBooking' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
  'getService' : IDL.Func([ServiceId], [IDL.Opt(Service)], ['query']),
  'getTeamMember' : IDL.Func([TeamMemberId], [IDL.Opt(TeamMember)], ['query']),
  'listBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'listTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingId = IDL.Nat;
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const TeamMemberId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ServiceId = IDL.Nat;
  const Booking = IDL.Record({
    'id' : BookingId,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'customerPhone' : IDL.Text,
    'teamMemberId' : IDL.Opt(TeamMemberId),
    'createdAt' : Timestamp,
    'preferredDateTime' : IDL.Text,
    'serviceId' : ServiceId,
    'customerEmail' : IDL.Text,
  });
  const BookingResult = IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text });
  const BookingRequest = IDL.Record({
    'customerName' : IDL.Text,
    'customerPhone' : IDL.Text,
    'teamMemberId' : IDL.Opt(TeamMemberId),
    'preferredDateTime' : IDL.Text,
    'serviceId' : ServiceId,
    'customerEmail' : IDL.Text,
  });
  const ServiceCategory = IDL.Variant({
    'fade' : IDL.Null,
    'haircut' : IDL.Null,
    'beardTrim' : IDL.Null,
    'lineup' : IDL.Null,
  });
  const Service = IDL.Record({
    'id' : ServiceId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'category' : ServiceCategory,
    'price' : IDL.Nat,
  });
  const TeamMember = IDL.Record({
    'id' : TeamMemberId,
    'name' : IDL.Text,
    'specialty' : IDL.Text,
  });
  
  return IDL.Service({
    'cancelBooking' : IDL.Func([BookingId], [BookingResult], []),
    'createBooking' : IDL.Func([BookingRequest], [BookingResult], []),
    'getBooking' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
    'getService' : IDL.Func([ServiceId], [IDL.Opt(Service)], ['query']),
    'getTeamMember' : IDL.Func(
        [TeamMemberId],
        [IDL.Opt(TeamMember)],
        ['query'],
      ),
    'listBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'listTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };