/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ServiceId = bigint;
export type BookingId = bigint;
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Service {
    id: ServiceId;
    name: string;
    description: string;
    durationMinutes: bigint;
    category: ServiceCategory;
    price: bigint;
}
export type BookingResult = {
    __kind__: "ok";
    ok: Booking;
} | {
    __kind__: "err";
    err: string;
};
export interface CheckoutRequest {
    customerName: string;
    cancelUrl: string;
    customerPhone: string;
    teamMemberId?: TeamMemberId;
    preferredDateTime: string;
    serviceIds: Array<ServiceId>;
    customerEmail: string;
    successUrl: string;
}
export type CheckoutSessionResult = {
    __kind__: "ok";
    ok: {
        checkoutUrl: string;
        sessionId: string;
    };
} | {
    __kind__: "err";
    err: string;
};
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type TeamMemberId = bigint;
export interface TeamMember {
    id: TeamMemberId;
    name: string;
    specialty: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface Booking {
    id: BookingId;
    customerName: string;
    status: BookingStatus;
    paymentStatus: PaymentStatus;
    customerPhone: string;
    teamMemberId?: TeamMemberId;
    createdAt: Timestamp;
    preferredDateTime: string;
    serviceIds: Array<ServiceId>;
    referenceCode: string;
    totalAmount: bigint;
    stripeSessionId?: string;
    customerEmail: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum PaymentStatus {
    paid = "paid",
    unpaid = "unpaid"
}
export enum ServiceCategory {
    fade = "fade",
    haircut = "haircut",
    beardTrim = "beardTrim",
    lineup = "lineup"
}
export interface backendInterface {
    cancelBooking(id: BookingId): Promise<BookingResult>;
    confirmBookingAfterPayment(stripeSessionId: string): Promise<BookingResult>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createStripeCheckoutSession(req: CheckoutRequest): Promise<CheckoutSessionResult>;
    getBooking(id: BookingId): Promise<Booking | null>;
    getService(id: ServiceId): Promise<Service | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTeamMember(id: TeamMemberId): Promise<TeamMember | null>;
    isStripeConfigured(): Promise<boolean>;
    listAllBookings(): Promise<Array<Booking>>;
    listBookings(): Promise<Array<Booking>>;
    listBookingsByDate(dateStr: string): Promise<Array<Booking>>;
    listFutureBookings(): Promise<Array<Booking>>;
    listServices(): Promise<Array<Service>>;
    listTeamMembers(): Promise<Array<TeamMember>>;
    markBookingPaid(id: BookingId): Promise<BookingResult>;
    setStripeConfiguration(secretKey: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { Booking as _Booking, BookingId as _BookingId, BookingResult as _BookingResult, BookingStatus as _BookingStatus, CheckoutRequest as _CheckoutRequest, CheckoutSessionResult as _CheckoutSessionResult, PaymentStatus as _PaymentStatus, Service as _Service, ServiceCategory as _ServiceCategory, ServiceId as _ServiceId, StripeSessionStatus as _StripeSessionStatus, TeamMember as _TeamMember, TeamMemberId as _TeamMemberId, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async cancelBooking(arg0: BookingId): Promise<BookingResult> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return from_candid_BookingResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return from_candid_BookingResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async confirmBookingAfterPayment(arg0: string): Promise<BookingResult> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmBookingAfterPayment(arg0);
                return from_candid_BookingResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmBookingAfterPayment(arg0);
            return from_candid_BookingResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createStripeCheckoutSession(arg0: CheckoutRequest): Promise<CheckoutSessionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createStripeCheckoutSession(to_candid_CheckoutRequest_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CheckoutSessionResult_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStripeCheckoutSession(to_candid_CheckoutRequest_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CheckoutSessionResult_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooking(arg0: BookingId): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getService(arg0: ServiceId): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamMember(arg0: TeamMemberId): Promise<TeamMember | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamMember(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamMember(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllBookings();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllBookings();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBookings();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBookings();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBookingsByDate(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBookingsByDate(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBookingsByDate(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFutureBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFutureBookings();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFutureBookings();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.listServices();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listServices();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTeamMembers(): Promise<Array<TeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeamMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTeamMembers();
            return result;
        }
    }
    async markBookingPaid(arg0: BookingId): Promise<BookingResult> {
        if (this.processError) {
            try {
                const result = await this.actor.markBookingPaid(arg0);
                return from_candid_BookingResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markBookingPaid(arg0);
            return from_candid_BookingResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setStripeConfiguration(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_BookingResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingResult): BookingResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_CheckoutSessionResult_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CheckoutSessionResult): CheckoutSessionResult {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Service]): Service | null {
    return value.length === 0 ? null : from_candid_Service_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeamMember]): TeamMember | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeamMemberId]): TeamMemberId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ServiceId;
    name: string;
    description: string;
    durationMinutes: bigint;
    category: _ServiceCategory;
    price: bigint;
}): {
    id: ServiceId;
    name: string;
    description: string;
    durationMinutes: bigint;
    category: ServiceCategory;
    price: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        durationMinutes: value.durationMinutes,
        category: from_candid_ServiceCategory_n19(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookingId;
    customerName: string;
    status: _BookingStatus;
    paymentStatus: _PaymentStatus;
    customerPhone: string;
    teamMemberId: [] | [_TeamMemberId];
    createdAt: _Timestamp;
    preferredDateTime: string;
    serviceIds: Array<_ServiceId>;
    referenceCode: string;
    totalAmount: bigint;
    stripeSessionId: [] | [string];
    customerEmail: string;
}): {
    id: BookingId;
    customerName: string;
    status: BookingStatus;
    paymentStatus: PaymentStatus;
    customerPhone: string;
    teamMemberId?: TeamMemberId;
    createdAt: Timestamp;
    preferredDateTime: string;
    serviceIds: Array<ServiceId>;
    referenceCode: string;
    totalAmount: bigint;
    stripeSessionId?: string;
    customerEmail: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_BookingStatus_n5(_uploadFile, _downloadFile, value.status),
        paymentStatus: from_candid_PaymentStatus_n7(_uploadFile, _downloadFile, value.paymentStatus),
        customerPhone: value.customerPhone,
        teamMemberId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.teamMemberId)),
        createdAt: value.createdAt,
        preferredDateTime: value.preferredDateTime,
        serviceIds: value.serviceIds,
        referenceCode: value.referenceCode,
        totalAmount: value.totalAmount,
        stripeSessionId: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.stripeSessionId)),
        customerEmail: value.customerEmail
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        checkoutUrl: string;
        sessionId: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        checkoutUrl: string;
        sessionId: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Booking;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Booking;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Booking_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fade: null;
} | {
    haircut: null;
} | {
    beardTrim: null;
} | {
    lineup: null;
}): ServiceCategory {
    return "fade" in value ? ServiceCategory.fade : "haircut" in value ? ServiceCategory.haircut : "beardTrim" in value ? ServiceCategory.beardTrim : "lineup" in value ? ServiceCategory.lineup : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n23(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    unpaid: null;
}): PaymentStatus {
    return "paid" in value ? PaymentStatus.paid : "unpaid" in value ? PaymentStatus.unpaid : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n17(_uploadFile, _downloadFile, x));
}
function to_candid_CheckoutRequest_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CheckoutRequest): _CheckoutRequest {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    cancelUrl: string;
    customerPhone: string;
    teamMemberId?: TeamMemberId;
    preferredDateTime: string;
    serviceIds: Array<ServiceId>;
    customerEmail: string;
    successUrl: string;
}): {
    customerName: string;
    cancelUrl: string;
    customerPhone: string;
    teamMemberId: [] | [_TeamMemberId];
    preferredDateTime: string;
    serviceIds: Array<_ServiceId>;
    customerEmail: string;
    successUrl: string;
} {
    return {
        customerName: value.customerName,
        cancelUrl: value.cancelUrl,
        customerPhone: value.customerPhone,
        teamMemberId: value.teamMemberId ? candid_some(value.teamMemberId) : candid_none(),
        preferredDateTime: value.preferredDateTime,
        serviceIds: value.serviceIds,
        customerEmail: value.customerEmail,
        successUrl: value.successUrl
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
