/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ServiceId = bigint;
export type BookingId = bigint;
export type Timestamp = bigint;
export type TeamMemberId = bigint;
export interface BookingRequest {
    customerName: string;
    customerPhone: string;
    teamMemberId?: TeamMemberId;
    preferredDateTime: string;
    serviceId: ServiceId;
    customerEmail: string;
}
export interface TeamMember {
    id: TeamMemberId;
    name: string;
    specialty: string;
}
export interface Service {
    id: ServiceId;
    name: string;
    description: string;
    durationMinutes: bigint;
    category: ServiceCategory;
    price: bigint;
}
export type BookingResult = {
    __kind__: "ok";
    ok: Booking;
} | {
    __kind__: "err";
    err: string;
};
export interface Booking {
    id: BookingId;
    customerName: string;
    status: BookingStatus;
    customerPhone: string;
    teamMemberId?: TeamMemberId;
    createdAt: Timestamp;
    preferredDateTime: string;
    serviceId: ServiceId;
    customerEmail: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum ServiceCategory {
    fade = "fade",
    haircut = "haircut",
    beardTrim = "beardTrim",
    lineup = "lineup"
}
export interface backendInterface {
    cancelBooking(id: BookingId): Promise<BookingResult>;
    createBooking(req: BookingRequest): Promise<BookingResult>;
    getBooking(id: BookingId): Promise<Booking | null>;
    getService(id: ServiceId): Promise<Service | null>;
    getTeamMember(id: TeamMemberId): Promise<TeamMember | null>;
    listBookings(): Promise<Array<Booking>>;
    listServices(): Promise<Array<Service>>;
    listTeamMembers(): Promise<Array<TeamMember>>;
}
import type { Booking as _Booking, BookingId as _BookingId, BookingRequest as _BookingRequest, BookingResult as _BookingResult, BookingStatus as _BookingStatus, Service as _Service, ServiceCategory as _ServiceCategory, ServiceId as _ServiceId, TeamMember as _TeamMember, TeamMemberId as _TeamMemberId, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async cancelBooking(arg0: BookingId): Promise<BookingResult> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return from_candid_BookingResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return from_candid_BookingResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBooking(arg0: BookingRequest): Promise<BookingResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_BookingRequest_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BookingResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_BookingRequest_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BookingResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooking(arg0: BookingId): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getService(arg0: ServiceId): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamMember(arg0: TeamMemberId): Promise<TeamMember | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamMember(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamMember(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBookings();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBookings();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.listServices();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listServices();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTeamMembers(): Promise<Array<TeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeamMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTeamMembers();
            return result;
        }
    }
}
function from_candid_BookingResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingResult): BookingResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Service]): Service | null {
    return value.length === 0 ? null : from_candid_Service_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeamMember]): TeamMember | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeamMemberId]): TeamMemberId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ServiceId;
    name: string;
    description: string;
    durationMinutes: bigint;
    category: _ServiceCategory;
    price: bigint;
}): {
    id: ServiceId;
    name: string;
    description: string;
    durationMinutes: bigint;
    category: ServiceCategory;
    price: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        durationMinutes: value.durationMinutes,
        category: from_candid_ServiceCategory_n14(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookingId;
    customerName: string;
    status: _BookingStatus;
    customerPhone: string;
    teamMemberId: [] | [_TeamMemberId];
    createdAt: _Timestamp;
    preferredDateTime: string;
    serviceId: _ServiceId;
    customerEmail: string;
}): {
    id: BookingId;
    customerName: string;
    status: BookingStatus;
    customerPhone: string;
    teamMemberId?: TeamMemberId;
    createdAt: Timestamp;
    preferredDateTime: string;
    serviceId: ServiceId;
    customerEmail: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_BookingStatus_n5(_uploadFile, _downloadFile, value.status),
        customerPhone: value.customerPhone,
        teamMemberId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.teamMemberId)),
        createdAt: value.createdAt,
        preferredDateTime: value.preferredDateTime,
        serviceId: value.serviceId,
        customerEmail: value.customerEmail
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fade: null;
} | {
    haircut: null;
} | {
    beardTrim: null;
} | {
    lineup: null;
}): ServiceCategory {
    return "fade" in value ? ServiceCategory.fade : "haircut" in value ? ServiceCategory.haircut : "beardTrim" in value ? ServiceCategory.beardTrim : "lineup" in value ? ServiceCategory.lineup : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Booking;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Booking;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Booking_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n12(_uploadFile, _downloadFile, x));
}
function to_candid_BookingRequest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingRequest): _BookingRequest {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    customerPhone: string;
    teamMemberId?: TeamMemberId;
    preferredDateTime: string;
    serviceId: ServiceId;
    customerEmail: string;
}): {
    customerName: string;
    customerPhone: string;
    teamMemberId: [] | [_TeamMemberId];
    preferredDateTime: string;
    serviceId: _ServiceId;
    customerEmail: string;
} {
    return {
        customerName: value.customerName,
        customerPhone: value.customerPhone,
        teamMemberId: value.teamMemberId ? candid_some(value.teamMemberId) : candid_none(),
        preferredDateTime: value.preferredDateTime,
        serviceId: value.serviceId,
        customerEmail: value.customerEmail
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
